name: Release

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          path: master
          ref: master
          token: ${{ secrets.GH_CI_TOKEN }}

      - name: Get release tag from XML
        id: xml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '/project/version/text()'

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.xml.outputs.info }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_TOKEN }}
