name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get deps
        run: mvn dependency:go-offline -B

      - name: Build service
        run: mvn clean install -Dsurefire.useSystemClassLoader=false

      - name: Extract tag names
        id: tags
        uses: actions/github-script@v4
        with:
          script: return context.payload.ref.replace(/^refs\/tags\/v/, '')

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_TOKEN }}