name: Build

on:
  push:
    branches:
      - config

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          path: master
          ref: master
          token: ${{ secrets.GH_CI_TOKEN }}

      - name: Check out the config
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          path: config
          ref: config
          token: ${{ secrets.GH_CI_TOKEN }}

      - name: Generate files with constants
        uses: matrixbotio/constants@generator-action
        with:
          config-path: "$GITHUB_WORKSPACE/config"
          dest-path: "$GITHUB_WORKSPACE/master"

      - name: Push generated
        run: |
          cd "$GITHUB_WORKSPACE"/config
          export SHA=$(git rev-parse --short HEAD)
          cd "$GITHUB_WORKSPACE"/master
          if [ $(git diff --name-status | wc -l) -ne 0 ]; then
            git config --global user.email "82820230+MatrixDevBot@users.noreply.github.com"
            git config --global user.name "Matrix Dev [BOT]"
            git add .
            git commit -m "Update constants ($SHA)"
            git push origin master
          fi
