name: Packages

on:
  release:

jobs:
  java-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get deps
        run: mvn dependency:go-offline -B

      - name: Build service
        run: mvn clean install -Dsurefire.useSystemClassLoader=false

      - name: Publish package
        run: mvn --batch-mode deploy
